mysite/apps/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
		path('', views.index0, name ='index0'),
		path('<int:article_id>/', views.detail, name ='detail'),
		path('<int:article_id>/leave_comment/', views.leave_comment, name ='leave_comment'),
		path('test/', views.test, name ='test')
	]

mysite/apps/polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name ='index')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')), 
    path('articles/', include('articles.urls')),
]

mysite/apps/articles/models.py
from django.db import models
import datetime
from django.utils import timezone

class Article(models.Model):
    article_title = models.CharField('название статьи', max_length = 200)
    author_name = models.CharField('имя автора', max_length = 50, default = 'anon')
    article_text = models.TextField('текст статьи')
    pub_date = models.DateTimeField('дата публикации')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= ( timezone.now() - datetime.timedelta(days = 7) )

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def publish(self):
        self.pub_date = timezone.now()
        self.save()

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_name = models.CharField('имя автора', max_length = 50)
    comment_text = models.CharField('текст комментария', max_length = 200)
    pub_date = models.DateTimeField('дата публикации', default = timezone.now())

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

mysite/apps/polls/models.py
from django.db import models

# Create your models here.

mysite/apps/articles/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Article

def index0(request):
	latest_articles_list = Article.objects.order_by('-pub_date')[:5]
	return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})

def test(request):
	return HttpResponse('ТЕСТОВАЯ СТРАНИЦА')

def detail(request, article_id):
	try:
		a = Article.objects.get( id =  article_id )
	except:
		raise Http404('Статья не найдена')
	latest_comments_list = a.comment_set.order_by('-id')[:10]
	return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})

def leave_comment(request, article_id):
	try:
		a = Article.objects.get( id =  article_id)
	except:
		raise Http404('Статья не найдена')
	a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])
	return HttpResponseRedirect(reverse('articles:detail', args  = (a.id, )))

mysite/apps/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
	return HttpResponse('Привет, мир!')

mysite/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}
<a href="/articles"> Назад к списку статей </a>
<h1>{{article.article_title}}</h1>
{% if article.was_published_recently %}
<em>СВЕЖАЯ СТАТЬЯ!</em>

<p>{{article.article_text}}</p>
{% endif %}
<em>{{article.pub_date}}</em>


<hr>
{% if latest_comments_list %}
    {% for c in latest_comments_list %}
        <p>
            <strong>{{c.author_name}}</strong>
            {{c.comment_text}}
            <br /><em>{{c.pub_date}}</em>
        </p>
    {% endfor %}
{% else %}
Комментарии не найдены
{% endif %}
<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="post">
    {% csrf_token %}
    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required="" placeholder="Тект комментария" cols="30" rows="10"></textarea><br>
    <button type="submit">Оставить комментарий</button>
</form>

{% endblock %}

mysite/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}
    <h1>Последние статьи</h1>
    {% if latest_articles_list %}
        {% for a in latest_articles_list %}
            <div>
                <h2><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></h2>
                <p>Опубликовано: {{a.pub_date}}</p>
            </div>
        {% endfor %}
    {% else %}
        Статьи не найдены =(
    {% endif %}
{% endblock %}

mysite/templates/articles/map.html
{% extends 'base.html' %}

{% block title %}Меню{% endblock %}

{% block content %}
<p><a href="/articles">Статьи</a> </p>
<p><a href="/polls">Опросы</a> </p>
{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Мой сайт. {% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>